<?php namespace uVicate;
include_once __DIR__.'/Object.php';

/**
 * The Member class handles the authentication process of an user, password, lost password, etc. It has nothing to do with the personal information.
 */
class Member extends User {
	private $_url;

	/**
	 * Starts the database configuration
	 */
	protected function initdb(){
		parent::initdb();

		$this->_url = $GLOBALS['url'];
	}

	/**
	 * Does the user exists? this function will look for it in the DB
	 * @param  string $username Username
	 * @param  string $password Password
	 * @return bool           true if the user is correct
	 */
	private function exists($username, $password){
		$query = $this->_fdb->from('users')->select(null)->select('user_id AS id, password')->where('username = ?', $username);
		$data = $query->fetch();
		if(!$data){
			return false;
		}

		$id = $data['id'];
		$this->id = $id;

		$hash = $data['password'];
		$verif2 = $this->verify_password($password, $hash);

		return $verif2;
	}

	/**
	 * To be able to register a login, a keypass is created, this will be stored in the database and cookie
	 * @param string $table Tablename to verify if keypass exists
	 * @return string 60 character-long string
	 */
	private function create_key_pass($table = 'login'){
		$abc = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_[]{}';
		$k =  substr(str_shuffle($abc), 0, 60);

		//Verifies that it doesn't exist
		$v = $this->validate_key_pass($table, $k);
		if(!$v){
			return $k;
		}else{
			return $this->create_key_pass();
		}
	}

	/**
	 * For each login and for each lost password, a key_pass is created, in different tables of course. But the validation for is existance is the same for each case, so this function checks if the key_pass exists or not.
	 * @param  string  $table    name of the table in which the key pass is stored
	 * @param  string  $k        keypass to validate
	 * @param  int  $id       user's id, in case the keypass is validated against a certain user
	 * @param  boolean $complete if true, it will return the complete DB row
	 * @return bool|array            The array consists in the row in which the keypass is stored within the DB | true if the keypass exists, false if it doesn't
	 */
	private function validate_key_pass($table, $k, $id = null, $complete = false){
		$where = array('keypass' => $k);
		if($id != null){
			$where['user_id'] = $id;
		}

		$query = $this->_fdb->from($table)->where($where);
		$data = $query->fetch();
		if(!$data){
			return false;
		}else{
			if($complete){
				return $data;
			}else{
				return true;
			}
		}
	}

	/**
	 * Saves the login in the database
	 * @param  array $time    Array generated in calculate_times()
	 * @param  string $keypass String generated in create_key_pass()
	 * @return int          data taken from PDO execute()
	 */
	private function register_login($time, $keypass){
		$now = date('Y-m-d H:i:s');
		$data = array(
			'user_id' => $this->id,
			'date' => $now,
			'expiracy' => date('Y-m-d H:i:s', $time['pass']),
			'keypass' => $keypass,
			'active' => 1
			);

		$query = $this->_fdb->insertInto('login')->values($data);
		return $query->execute();
	}

	/**
	 * Calculates the time of duration for the cookies
	 * @param  integer $plus 1 if is for calculate time in future, -1 if is going to be used to destroy cookies
	 * @return array        Time for the userid and password cookies
	 */
	private function calculate_times($plus = 1){
		$time = array();
		$time['auth'] = time() + (($GLOBALS['auth_time'] / 1000) * $plus);
		$time['pass'] = time() + (($GLOBALS['pass_time'] / 1000) * $plus);

		return $time;
	}

	/**
	 * Register user's cookies
	 * @param  string $k Keypass generated by create_key_pass()
	 * @param  array $t Array generated by calculate_times()
	 * @return null    No response
	 */
	private function register_cookies($k, $t){
		foreach ($GLOBALS['cookie_domains'] as $domain) {
			//Set the identification cookie
			setcookie($GLOBALS['auth_cookie'], $this->id, $t['auth'], "/", $domain, $GLOBALS['secure_cookie']);
			setcookie($GLOBALS['auth_cookie'], $this->id, $t['auth'], "/", "", $GLOBALS['secure_cookie']);

			//Set the keypass cookie
			setcookie($GLOBALS['pass_cookie'], $k, $t['pass'], "/", $domain, $GLOBALS['secure_cookie']);
			setcookie($GLOBALS['pass_cookie'], $k, $t['pass'], "/", "", $GLOBALS['secure_cookie']);
		}
	}

	/**
	 * Validates the login keypass of an user (created and stored in a cookie)
	 * @param  int $id      User id
	 * @param  string $keypass Key pass
	 * @return array          success => false if false, success => true if true
	 */
	public function verify_credentials($id, $keypass){
		$data = $this->validate_key_pass('login', $keypass, $id, true);
		$r =  array('success' => false);
		if($data){
			if((int)$data['active'] == 1){
				$r = array('success' => true, 'user_id' => $id);
			}
		}

		return $this->handleResponse($r);
	}
	
	/**
	 * Calls the required methods to perform a succesful login
	 * @param  string $username user's username
	 * @param  string $password user's password
	 * @return int           data returned by register_login()
	 */
	public function login($username, $password){

		$r = array('success' => false);

		if($this->exists($username, $password)){
			$t = $this->calculate_times();
			$k = $this->create_key_pass();
			$this->register_cookies($k, $t);

			$q = $this->register_login($t, $k);
			if($q){
				$r = array('success' => true);
			}
		}

		return $this->handleResponse($r);
	}

	/**
	 * Method called when user manually closes session (logout button) it destroys the current cookies and deactivates the DB keypass
	 * @return null No return
	 */
	public function logout(){
		$t = $this->calculate_times(-1);
		$this->deactivate_keypass();
		$this->register_cookies("", $t);
	}

	/**
	 * When user is having login issues, this method will force a user to logout.
	 * @return null No return
	 */
	public function force_logout(){
		$this->deactivate_keypass();
	}

	/**
	 * Sets to inactive the current active deactivate_keypass
	 * @return boolean         true if the keypass was deactivated
	 */
	private function deactivate_keypass(){
		$key = $_COOKIE[$GLOBALS['pass_cookie']];
		if($key != ''){
			$query = $this->_fdb->update('login')->set(array('active' => 0))->where('keypass', $key);
			$query->execute();
			return true;
		}else{
			return false;
		}
	}

	/**
	 * This function will send an email to a user that forgot its password
	 * @param  string $username username
	 * @return boolean           true if the email was correctly sent
	 */
	public function forgotten_password($username){
		//Get user id
		if(!$this->id){
			$query = $this->_fdb->from('users')->select(null)->select('user_id AS id')->where('username = ?', $username);
			$data = $query->fetch();
			if(!$data){
				return false;
			}

			$this->id = $data['id'];
		}

		$data = array();

		$now = date('Y-m-d H:i:s');
		$expiracy = strtotime($now) + 60 * 60 * 2; // Add two hours
		$expiracy = date('Y-m-d H:i:s', $expiracy);
		$data['date'] = $now;
		$data['expiracy'] = $expiracy;
		$data['user_id'] = $this->id;

		$key = $this->create_key_pass('forgotten_password');
		$data['keypass'] = $key;

		$url = $this->build_forgotten_url($key);
		$this->send_forgotten_email($url);

		$query = $this->_fdb->insertInto('forgotten_password')->values($data);
		$query->execute();
		return true;
	}

	/**
	 * Creates the URL that the user will click in order to reestablish his or her password
	 * @param  string $key keypass created to validate the operation
	 * @return string      the created URL
	 */
	private function build_forgotten_url($key){
		$url = $this->_url . 'oauth/authorize/forgotten_password.php?id=' . $this->id . '&key=' . $key;

		return $url;
	}

	/**
	 * Sends the email with the instructions to reset the password
	 * @param  string $url URL created to reestablish the password
	 * @return boolean      true if it is correct
	 */
	private function send_forgotten_email($url){
		$data = array(
			'title' => 'Forgotten password request',
			'description' => "A request has been made, if you didn't make this request, don't pay attention to this email.",
			'url' => $url,
			'here' => 'Here'
			);

		$dom = file_get_contents(__DIR__.'/../../oauth/authorize/forgotten_email.html');
		foreach ($data as $key => $value) {
			$dom = str_replace("#" . $key . "#", $value, $dom);
		}

		$user = $this->fetch_basic();

		$headers  = 'MIME-Version: 1.0' . "\r\n";
		$headers .= 'Content-type: text/html; charset=utf8' . "\r\n";
		mail($user['email'], $data['title'], $dom, $headers);

		return true;
	}

	/**
	 * Validates if the received keypass and user id are correct in order to reset the password
	 * @param  int $id      User's id which made the petition to reset the current password
	 * @param  string $keypass Keypass generated and sent to the user's email
	 * @return boolean          true if is correct
	 */
	public function validate_forgotten($id, $keypass){
		$where = array('keypass' => $keypass, 'user_id' => $id);
		$query = $this->_fdb->from('forgotten_password')->select(null)->select('keypass, expiracy, recovered')->where($where);
		$data = $query->fetch();
		if(!$data){
			return false;
		}else{
			$now = date('Y-m-d H:i:s');
			$now = strtotime($now);
			$expiracy = $data['expiracy'];
			$expiracy = strtotime($expiracy);

			if($now > $expiracy){
				return false;
			}

			if((int)$data['recovered'] === 1){
				return false;
			}

			return true;
		}
	}

	/**
	 * Resets the current password of an user, completes the operation of a forgotten password and deactivates all current active keypasses in order to ask again for each active session
	 * @param  int $id      User id
	 * @param  string $keypass Keypass
	 * @return boolean          true if is correct
	 */
	public function complete_forgotten($id, $keypass){
		$validate = $this->validate_forgotten($id, $keypass);

		if($validate){
			//Deletes al active keys
			$query = $this->_fdb->update('login')->set(array('active' => 0))->where('user_id', $id);
			$query->execute();

			$query = $this->_fdb->update('forgotten_password')->set(array('recovered' => 1))->where('keypass', $keypass);
			$query->execute();
			return true;
		}else{
			return false;
		}
	}

	public function activate(){

	}

	public function deactivate(){

	}
}

?>